name: Python CI

permissions: { }

on:
  push:
    paths-ignore:
      - docs/
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - docs/
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: "Build project and run unit tests"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      # GitHub caches the Python versions alongside the runner so it's faster than allow uv to manage them
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.17"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ruff checks
        run: uv run ruff check

      - name: Run ruff format
        run: uv run ruff format --check

      - name: Run mypy type checking
        run: uv run mypy . --exclude dist --exclude docs --exclude tests

      - name: Build
        run: uv build

      - name: Run tests
        run: uv run pytest -s -vv